create table if not exists "AppUsers" (
    "Id" integer generated by default as identity primary key,
    "FullName" varchar(120) not null,
    "Email" varchar(180) not null unique,
    "Role" varchar(30) not null default 'Student',
    "CreatedAt" timestamp with time zone not null default now()
);

create table if not exists "ClassRooms" (
    "Id" integer generated by default as identity primary key,
    "Name" varchar(100) not null,
    "Section" varchar(60) not null,
    "Subject" varchar(100) not null,
    "Description" varchar(500) not null default '',
    "CreatedAt" timestamp with time zone not null default now(),
    constraint "UX_ClassRooms_Name_Section_Subject" unique ("Name", "Section", "Subject")
);

create table if not exists "ClassMemberships" (
    "Id" integer generated by default as identity primary key,
    "ClassRoomId" integer not null references "ClassRooms" ("Id") on delete cascade,
    "AppUserId" integer not null references "AppUsers" ("Id") on delete cascade,
    "JoinedAt" timestamp with time zone not null default now(),
    constraint "UX_ClassMemberships_ClassRoomId_AppUserId" unique ("ClassRoomId", "AppUserId")
);

create table if not exists "ContentItems" (
    "Id" integer generated by default as identity primary key,
    "ClassRoomId" integer not null references "ClassRooms" ("Id") on delete cascade,
    "SubmittedById" integer null references "AppUsers" ("Id") on delete set null,
    "SubmittedByName" varchar(120) not null,
    "Title" varchar(160) not null,
    "Description" varchar(2000) not null default '',
    "ExternalUrl" varchar(600) null,
    "ContentType" varchar(40) not null,
    "Status" varchar(40) not null default 'Pending',
    "SubmittedAt" timestamp with time zone not null default now(),
    "ReviewedAt" timestamp with time zone null
);

create table if not exists "ContentFiles" (
    "Id" integer generated by default as identity primary key,
    "ContentItemId" integer not null references "ContentItems" ("Id") on delete cascade,
    "Provider" varchar(60) not null,
    "PublicId" varchar(250) not null,
    "Url" varchar(800) not null,
    "SecureUrl" varchar(800) not null,
    "OriginalFileName" varchar(255) not null,
    "MimeType" varchar(80) not null,
    "FileSize" bigint not null,
    "UploadedAt" timestamp with time zone not null default now()
);

create table if not exists "ContentReviews" (
    "Id" integer generated by default as identity primary key,
    "ContentItemId" integer not null references "ContentItems" ("Id") on delete cascade,
    "Decision" varchar(40) not null,
    "ReviewedByName" varchar(120) not null,
    "AdminNote" varchar(1000) not null default '',
    "ReviewedAt" timestamp with time zone not null default now()
);

create index if not exists "IX_ContentItems_ClassRoomId_Status_SubmittedAt"
    on "ContentItems" ("ClassRoomId", "Status", "SubmittedAt");

create index if not exists "IX_ContentFiles_PublicId"
    on "ContentFiles" ("PublicId");
