drop table if exists "ContentReviews" cascade;
drop table if exists "ClassMemberships" cascade;
drop table if exists "AppUsers" cascade;

do $$
begin
    if to_regclass('"ClassRooms"') is not null and to_regclass('class_rooms') is null then
        alter table "ClassRooms" rename to class_rooms;
    end if;

    if to_regclass('"ContentItems"') is not null and to_regclass('content_items') is null then
        alter table "ContentItems" rename to content_items;
    end if;

    if to_regclass('"ContentFiles"') is not null and to_regclass('content_files') is null then
        alter table "ContentFiles" rename to content_files;
    end if;
end $$;

create table if not exists class_rooms (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    section varchar(60) not null,
    subject varchar(100) not null,
    description varchar(500) not null default '',
    created_at timestamp with time zone not null default now(),
    constraint ux_class_rooms_name_section_subject unique (name, section, subject)
);

create table if not exists content_items (
    id integer generated by default as identity primary key,
    class_room_id integer not null references class_rooms (id) on delete cascade,
    submitted_by_name varchar(120) not null,
    title varchar(160) not null,
    description varchar(2000) not null default '',
    external_url varchar(600) null,
    content_type varchar(40) not null,
    status varchar(40) not null default 'Pending',
    submitted_at timestamp with time zone not null default now(),
    reviewed_at timestamp with time zone null
);

create table if not exists content_files (
    id integer generated by default as identity primary key,
    content_item_id integer not null references content_items (id) on delete cascade,
    provider varchar(60) not null,
    resource_type varchar(30) not null default 'image',
    public_id varchar(250) not null,
    url varchar(800) not null,
    secure_url varchar(800) not null,
    original_file_name varchar(255) not null,
    mime_type varchar(80) not null,
    file_size bigint not null,
    uploaded_at timestamp with time zone not null default now()
);

do $$
begin
    if exists (select 1 from information_schema.columns where table_name = 'class_rooms' and column_name = 'Id') then
        alter table class_rooms rename column "Id" to id;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'class_rooms' and column_name = 'Name') then
        alter table class_rooms rename column "Name" to name;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'class_rooms' and column_name = 'Section') then
        alter table class_rooms rename column "Section" to section;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'class_rooms' and column_name = 'Subject') then
        alter table class_rooms rename column "Subject" to subject;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'class_rooms' and column_name = 'Description') then
        alter table class_rooms rename column "Description" to description;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'class_rooms' and column_name = 'CreatedAt') then
        alter table class_rooms rename column "CreatedAt" to created_at;
    end if;

    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'Id') then
        alter table content_items rename column "Id" to id;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'ClassRoomId') then
        alter table content_items rename column "ClassRoomId" to class_room_id;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'SubmittedByName') then
        alter table content_items rename column "SubmittedByName" to submitted_by_name;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'Title') then
        alter table content_items rename column "Title" to title;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'Description') then
        alter table content_items rename column "Description" to description;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'ExternalUrl') then
        alter table content_items rename column "ExternalUrl" to external_url;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'ContentType') then
        alter table content_items rename column "ContentType" to content_type;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'Status') then
        alter table content_items rename column "Status" to status;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'SubmittedAt') then
        alter table content_items rename column "SubmittedAt" to submitted_at;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'ReviewedAt') then
        alter table content_items rename column "ReviewedAt" to reviewed_at;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_items' and column_name = 'SubmittedById') then
        alter table content_items drop column "SubmittedById";
    end if;

    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'Id') then
        alter table content_files rename column "Id" to id;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'ContentItemId') then
        alter table content_files rename column "ContentItemId" to content_item_id;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'Provider') then
        alter table content_files rename column "Provider" to provider;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'ResourceType') then
        alter table content_files rename column "ResourceType" to resource_type;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'PublicId') then
        alter table content_files rename column "PublicId" to public_id;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'Url') then
        alter table content_files rename column "Url" to url;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'SecureUrl') then
        alter table content_files rename column "SecureUrl" to secure_url;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'OriginalFileName') then
        alter table content_files rename column "OriginalFileName" to original_file_name;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'MimeType') then
        alter table content_files rename column "MimeType" to mime_type;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'FileSize') then
        alter table content_files rename column "FileSize" to file_size;
    end if;
    if exists (select 1 from information_schema.columns where table_name = 'content_files' and column_name = 'UploadedAt') then
        alter table content_files rename column "UploadedAt" to uploaded_at;
    end if;
end $$;

alter table content_files
    add column if not exists resource_type varchar(30) not null default 'image';

create index if not exists ix_content_items_room_status_submitted
    on content_items (class_room_id, status, submitted_at);

create index if not exists ix_content_files_public_id
    on content_files (public_id);

update content_files
set
    resource_type = 'raw',
    url = replace(url, '/image/upload/', '/raw/upload/'),
    secure_url = replace(secure_url, '/image/upload/', '/raw/upload/')
where mime_type = 'application/pdf';
