create table if not exists class_rooms (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    section varchar(60) not null,
    subject varchar(100) not null,
    description varchar(500) not null default '',
    created_at timestamp with time zone not null default now(),
    constraint ux_class_rooms_name_section_subject unique (name, section, subject)
);

create table if not exists content_items (
    id integer generated by default as identity primary key,
    class_room_id integer not null references class_rooms (id) on delete cascade,
    submitted_by_name varchar(120) not null,
    title varchar(160) not null,
    description varchar(2000) not null default '',
    external_url varchar(600) null,
    content_type varchar(40) not null,
    status varchar(40) not null default 'Pending',
    submitted_at timestamp with time zone not null default now(),
    reviewed_at timestamp with time zone null
);

create table if not exists content_files (
    id integer generated by default as identity primary key,
    content_item_id integer not null references content_items (id) on delete cascade,
    provider varchar(60) not null,
    resource_type varchar(30) not null default 'image',
    public_id varchar(250) not null,
    url varchar(800) not null,
    secure_url varchar(800) not null,
    original_file_name varchar(255) not null,
    mime_type varchar(80) not null,
    file_size bigint not null,
    uploaded_at timestamp with time zone not null default now()
);

create index if not exists ix_content_items_room_status_submitted
    on content_items (class_room_id, status, submitted_at);

create index if not exists ix_content_files_public_id
    on content_files (public_id);
